rhinstaller/python-simpleline

- simpleline/event_loop/__init__.py
- simpleline/event_loop/event_queue.py
- simpleline/event_loop/main_loop.py
- simpleline/render/renderer.py
- simpleline/render/screen_stack.py
- simpleline/render/ui_screen.py
- tests/__init__.py
- tests/event_queue_test.py
- tests/render_screen_test.py
- tests/renderer_test.py
- tests/screen_scheduler_test.py
- tests/screen_stack_test.py
Modal screens needs their own event loop. So execute a new loop for every modal screen. Also manage to which source belongs to which event queue.
This means that modal window will delay even the future signals from the old screens. Every new signal emitted from old screens will be add to the old (non-active) event loop. These signals will be processed after the modal window will be closed.
> Fix modal screens

- examples/basic/basic.py
- examples/entry_counter/entry_counter.py
- examples/hub_spoke/hub_spoke.py
- examples/ignore_continue/ignore_continue.py
- simpleline/base.py
- simpleline/event_loop/__init__.py
- simpleline/event_loop/signals.py
- simpleline/render/adv_widgets.py
- simpleline/render/containers.py
- simpleline/render/io_manager.py
- simpleline/render/screen/__init__.py
- simpleline/render/widgets.py
- tests/event_queue_test.py
- tests/render_screen_test.py
- tests/screen_scheduler_test.py
- tests/widgets_test.py
These containers are automatically printing widgets with a correct ordering and line wrapping.
Containers are able to automatically add labels (keys) for every item and react on user input on these labels by calling callbacks registered for these items.
These widgets should replace `ColumnWidget`, however, `ColumnWidget` can still be used for some specific use-cases.
> Add widget containers

- po/Makefile
More than one level of directories are now present in `simpleline`.
We need to find sources for `potfile` generation recursively now.
> Fix potfile generation

- simpleline/render/screen_scheduler.py
Quit message was used for the application quit `UIScreen`. This can also be contained inside of a quit screen.
Quit screen is now instance.
> Remove unused quit message

- examples/entry_counter/entry_counter.py
- simpleline/render/screen/__init__.py
- simpleline/render/screen_scheduler.py
- tests/render_screen_test.py
Anaconda is using `ready` property for spokes in GUI and TUI. To fix this collision the `ready` property in simpleline is renamed to `screen_ready`.
> Fix `ready` property collision with Anaconda

- simpleline/event_loop/event_queue.py
`Lock` from `threading` module is context manager which means it can be used with `with` statement. This is false positive for `pylint` which is fixed in `python3-astroid` package in version 1.5.3.
The `python3-astroid` 1.5.3. package is already in Fedora. However, it contains old version of `astroid` thanks to packaging error.
When this will be solved we can revert this PR.
> Add temporal pylint-disable for with Lock

- examples/entry_counter/entry_counter.py
- examples/hub_spoke/hub_spoke.py
- examples/ignore_continue/ignore_continue.py
- simpleline/__init__.py
- simpleline/render/__init__.py
- simpleline/render/adv_widgets.py
- simpleline/render/io_manager.py
- simpleline/render/screen/__init__.py
- tests/render_screen_test.py
- tests/widgets_test.py
From the user perspective the `UIScreen` is the only class using this `enum`.
> Move InputState next to UIScreen

- simpleline/event_loop/__init__.py
- simpleline/event_loop/main_loop.py
- simpleline/event_loop/signals.py
- simpleline/render/io_manager.py
- tests/event_loop_test.py
- tests/render_screen_test.py
- tests/ticket_machine_test.py
This is fix for concurrent access for the user input and also fix for recursive waiting on signal.
For this purpose new solution how to save user input is used. It is not recommended but you can get multiple inputs right now. <- Required for python-meh and other exception processing solutions.
To fix recursive signal waiting new synchronization mechanism was introduced. The name and everything is analogy, however, I don't know if the analogy is the correct one or if this is already exists, so suggestions are welcomed.
> Rework wait on input

- simpleline/render/screen_stack.py
- tests/scheduler_test.py
- tests/screen_stack_test.py
Save `None` instead of `[]` to `UIScreen` `args` parameter. This parameter is used in methods like `refresh()`.
It is also expected behavior when everywhere is default `None`.
> Keep backward compatibility for UIScreen args

- simpleline/event_loop/main_loop.py
- simpleline/render/screen_scheduler.py
- tests/screen_scheduler_test.py
Raising exception has one big disadvantage that everything after the exception rose won't be executed.
Fix do not render when modal screen ends.
Rename tests constants which were hard to read.
> Add possibility to end loop politely

- simpleline/render/screen/__init__.py
- tests/widgets_test.py
Missing line when screen was bigger than screen height. This is now fixed.
As a bonus the printing code should be much more readable.
> Master fix big screen printing

- simpleline/event_loop/main_loop.py
- simpleline/render/screen_scheduler.py
- tests/screen_scheduler_test.py
The `ExitMainLoop` exception should kill whole application not just inner loop.
> The ExitMainLoop exception should kill whole app

- simpleline/render/containers.py
The *Value Error* was printed to the console. Now it is a debug log output with more information.
> Remove leftover print in containers parsing input

- simpleline/render/containers.py
- tests/containers_test.py
- tests/widgets_test.py
The list container resolved item reversed from the end of the list when `0` or lower number was the user input. Worked the same as in python `list[-1]` construct.
Also add tests and move rest of the tests from the `widgets_test`.
------------------------------------------------------------------------------------
First two commits are from https://github.com/rhinstaller/python-simpleline/pull/30 will be rebased when that PR will be merged.
> Master fix list input processing

- simpleline/event_loop/__init__.py
- simpleline/event_loop/main_loop.py
- tests/event_loop_test.py
Quit callback in event loop now have an `args` argument which is passed to the callback.
Also rename it to `set_quit_callback()`.
Add test for the callback.
> Rename quit callback and add args there.

- simpleline/render/screen/__init__.py
- simpleline/render/screen_handler.py
- tests/screen_scheduler_test.py
`ScreenScheduler` was renamed to `ScreenHandler` and moved outside of `UIScreen` scope.
Now it feels more like pushing screen to scheduler.
It has every method static and these methods.
Result of this change:
Before:
`screen.push_screen()`
Now:
`ScreenHandler.push_screen(screen)`
> Screen scheduling is moved to ScreenHandler

- simpleline/render/screen_scheduler.py
Without this the application froze when the user canceling quitting process.
> Redraw after YesNoDialog modal window close

- simpleline/render/screen_scheduler.py
- tests/render_screen_test.py
The redraw signal was enqueued when instantiating `ScreenScheduler`. Which caused exception when the `process_signals()` method was called with empty screen stack.
> Redraw on first scheduled screen (#1487326)

- simpleline/render/io_manager.py
Exception is handled properly by `ScreenScheduler`.
> Fix exception in Screen input caused infinite loop

- python-simpleline.spec
- simpleline/event_loop/__init__.py
- simpleline/event_loop/event_queue.py
- simpleline/event_loop/glib_event_loop.py
- simpleline/event_loop/main_loop.py
- simpleline/event_loop/signals.py
- simpleline/event_loop/ticket_machine.py
- simpleline/render/io_manager.py
- simpleline/render/screen_scheduler.py
- tests/event_loop_test.py
- tests/glib_event_loop_test.py
- tests/glib_tests/__init__.py
- tests/glib_tests/event_loop_glib_test.py
- tests/glib_tests/render_screen_glib_test.py
- tests/glib_tests/screen_scheduler_glib_test.py
- tests/render_screen_test.py
- tests/screen_scheduler_test.py
- tests/ticket_machine_test.py
Most of the related old tests are also used GLib event loop.
This event loop is not required by the Simpleline package. You do not need to use it and if you want to use it, please add it as requires for your package / install it manually.
> Add glib event loop

- simpleline/render/adv_widgets.py
- simpleline/render/io_manager.py
- simpleline/render/screen/__init__.py
- simpleline/render/screen_scheduler.py
- simpleline/render/widgets.py
- tests/simpleline_tests/adv_widgets_test.py
- tests/simpleline_tests/render_screen_test.py
- tests/simpleline_tests/widgets_test.py
Add `GetInputScreen` and `GetPassInputScreen` for getting user input.
To enable support for the screens the UIScreen class was extended by these features:
* `no_separator` - do not print separator before screen
* `hiden_user_input` - hide user input (sensitive user input)
Also small fix in `HelpScreen` and calling of `getpass` function.
> Add edit screens

- simpleline/event_loop/__init__.py
- simpleline/event_loop/glib_event_loop.py
- simpleline/event_loop/main_loop.py
- simpleline/render/screen_scheduler.py
- simpleline/render/screen_stack.py
- tests/simpleline_tests/glib_tests/__init__.py
- tests/simpleline_tests/glib_tests/render_screen_glib_test.py
- tests/simpleline_tests/glib_tests/screen_scheduler_glib_test.py
- tests/simpleline_tests/render_screen_test.py
- tests/simpleline_tests/screen_stack_test.py
Also make the kill app behavior consistent through event loops.
To print screen stack in Anaconda I need to create a PR for Anaconda which will log the screen stack dump in case of exception.
> Dump screen stack on unhandled exception

- doc/api/screen.rst
- doc/guide.rst
- examples/02_ignore_continue/02_ignore_continue.py
- examples/07_divider/07_divider.py
- simpleline/render/adv_widgets.py
- simpleline/render/io_manager.py
- simpleline/render/screen/__init__.py
- simpleline/render/screen_scheduler.py
- tests/simpleline_tests/render_screen_test.py
Support new `PROCESSED_AND_REDRAW` and `PROCESSED_AND_CLOSE`.
This is just a shortcut for calling `redraw()` and `close()` methods before `PROCESSED` but it should really help with usability of Simpleline.
> Master support processed and refresh

- simpleline/render/widgets.py
- tests/simpleline_tests/widgets_test.py
When widget contained \n character at the end of the text this character
was skipped. Fix this behavior by extending the buffer at the end if
required.
> Add missing newline characters

- Makefile
The zanata package renamed between F28 and F27 which makes this check valid only for F28 and later. This commit makes the check able to work independent on package name; it just checks the binary.
Also this will make packaging for other distributions easier.
> Robust zanata check in the makefile

- simpleline/__init__.py
- simpleline/logging.py
The logging settings can't be changed once it is configured. This is especially bad in case of library. Use `NullHandler` which is recommended by Python 3 documentation.
https://docs.python.org/3/howto/logging.html#library-config
> Setup logging handler properly for a library

- simpleline/render/adv_widgets.py
The password dialog should be closed even if no password is provided.
Otherwise, it is not possible to continue, because the UI is blocked.
> Always close the password dialog

- Makefile
By default we want to create an archive with bdist_wheel which will also create metadata for PYPI distribution. However, dbist_wheel have another dependency package which may not be by default installed and it is not required for spec file creation at all.
Add setup.py arguments as Makefile variable.
> Add possibility to change setup.py arguments

- .packit.yaml
- python-simpleline.spec
Packit should create a downstream release pull request when a new upstream release is created.
> Enable packit auto release to Fedora

- Makefile
- tests/simpleline_tests/adv_widgets_test.py
- tests/simpleline_tests/containers_test.py
- tests/simpleline_tests/glib_tests/event_loop_glib_test.py
- tests/simpleline_tests/glib_tests/input_handler_glib_test.py
- tests/simpleline_tests/glib_tests/render_screen_glib_test.py
- tests/simpleline_tests/glib_tests/screen_scheduler_glib_test.py
- tests/simpleline_tests/render_screen_test.py
- tests/simpleline_tests/screen_scheduler_test.py
Before we used `from tests... import` which is fine if you want to test code but complicating usage of testing installed library. Problem is that to import tests folder you have to start from the repository root which will also add simpleline folder with all the sources to `PYTHONPATH`.
By using relative imports and removing `tests/__init__.py` we can start tests from the `tests` folder. That will remove move `PYTHONPATH` to `tests` instead of repository root.
Resolves: rhbz#1682886
> Use relative imports in tests

- simpleline/event_loop/event_queue.py
- simpleline/event_loop/main_loop.py
- simpleline/render/screen_scheduler.py
- simpleline/render/screen_stack.py
Use `raise from` where appropriate. Silence the warning for the
ScreenScheduler class where it exits the main loop, as that is not
really exception propagation.
> Fix raise-missing-from (W0707) pylint warnings

- .packit.yaml
This is not required anymore thanks to this fix:
https://github.com/packit/packit/issues/867#event-3791693297
_Waiting until the change will be released._
> Remove packit get-current-action

- .packit.yaml
This will enable us that we won't break future RHEL branching.
> Add fedora-eln for build and test execution

- .github/workflows/validate.yml
First, they are more up to date so we will avoid issue with bad GPG keys we have now.
Second, there is no limit for downloads.
> Use Fedora container registry instead of Dockerhub

- python-simpleline.spec
The make was removed from build-roots from F34 further. So we need to add it manually.
> Add missing make command to spec file

- simpleline/render/prompt.py
Translated prompt keys are not supported by the simpleline library,
so don't mark them for translation.
Related: rhbz#1892830
> Don't translate the prompt keys

- .pylintrc
- simpleline/event_loop/__init__.py
- simpleline/event_loop/glib_event_loop.py
- simpleline/event_loop/main_loop.py
Fix one correct issue and then disable this check globally because it can't be disabled locally (bug in pylint).
> Fix pylint duplicate code

- .packit.yaml
This alias will always point to the latests Fedora which is not Rawhide. That will enable us to just not care for this project.
> Switch to packit new fedora-latest alias

- .github/workflows/validate.yml
In fedora container the checkout GitHub action doesn't work. Let's use Fedora container only for test execution.
> Fix GitHub workflow checkout

- .packit.yaml
- Makefile
Tag will be named just by version, e.g. `1.8.1`. The `simpleline-1.8.1` prefix will not be used anymore.
That is the standard versioning. No need to add the prefix which only giving us problems everywhere.
Related to https://github.com/rhinstaller/python-simpleline/issues/102.
> Improve tag naming of this project

- .pylintrc
New warning introduced around pylint 2.11.1.
> Do not force using f-strings by pylint

- python-simpleline.spec
It's not a build require at all.
> Remove pocketlint from the build requires

- .github/dependabot.yml
Realistically, it will only bump actions/checkout once a year or so.
> Add dependabot updates for actions (#infra)

- .github/workflows/validate.yml
- Makefile
It is a small wrapper to run tests in a container with a pinned pylint version.
The pinned pylint version is required otherwise we would be still fixing pylint issues on this stable branch.
Use this new call also in the GH action.
> Add Makefile target for local container tests

- simpleline/input/input_handler.py
- simpleline/render/screen/__init__.py
- simpleline/render/screen/input_manager.py
- tests/units/main/adv_widgets_test.py
Backport of https://github.com/rhinstaller/python-simpleline/pull/111 .
> Add support to disable concurrency check

- .packit.yaml
This stable branch is released on centos-stream-9 so lets test the build there.
> Enable packit builds for centos-stream-9

- po/Makefile
Add a few arguments to the potfile
- package name
- package version
- copyright holder
- mail for bug reporting
- sort pot file output (so it stays the same all the time)
> Improve pot file generation
