examples/ignore_continue/ignore_continue.py, simpleline/event_loop/signal_handler.py, simpleline/event_loop/signals.py, simpleline/render/renderer.py, simpleline/render/ui_screen.py, tests/render_screen_test.py, tests/screen_scheduler_test.py
Close screen is now handled by signal as everything else.
=> Change close to signal

simpleline/render/screen/__init__.py
Add missing parameter to shortcut class.
Also remove useless return from `UIScreen`.
=> Add hidden parameter to UIScreen get input

simpleline/render/containers.py
This method is just a shortcut to calls:
`self.add()`
`self.add_separator()`
=> Add method add_with_separator to WindowContainer

simpleline/render/screen/scheduler_handler.py, simpleline/render/screen_scheduler.py
=> Add args param to the scheduler_handler shortcuts

simpleline/event_loop/event_queue.py
Add locks to the sources. We don't need to lock `PriorityQueue` this is a thread safe implementation.
=> Make the EventQueue thread safe

simpleline/event_loop/main_loop.py, simpleline/event_loop/signals.py
This will make possible for application to disable exception handling in the simpleline and handle exceptions other way.
=> Re-raise exception only when no handler available

simpleline/render/adv_widgets.py
Use `InputState`.
`Title` is not the class variable now.
Use the `WindowContainer.add_with_separator()` method.
=> Reflect changes in adv_widgets

simpleline/event_loop/__init__.py, simpleline/event_loop/main_loop.py, simpleline/logging.py, simpleline/render/io_manager.py, simpleline/render/screen/__init__.py, simpleline/render/screen_scheduler.py
For better logging the `__str__()` methods were implemented for `UIScreen` and `AbstractSignal`.
=> Add logging to the Simpleline

simpleline/__init__.py
This will be improved later to test if event loop and screen scheduler are running.
=> Add test if app is initialized

README.md
Documentation is build on readthedocs.
=> Add link to the documentation

doc/Makefile, doc/api.rst, doc/api/advanced_input.rst, doc/api/app.rst, doc/api/screen.rst
Also migrate to a python 3 sphinx module.
=> Add missing documentation

simpleline/event_loop/main_loop.py, simpleline/render/screen/input_manager.py, simpleline/render/screen_scheduler.py
Most solved by pylint disable but there is one improvement.
=> Fix pylint errors raised by new pylint version

Makefile
Suggested on pocketlint project by @vpodzime . Thanks!
=> Tweak date lang settings in make bumpver command

simpleline/errors.py, simpleline/event_loop/__init__.py, simpleline/event_loop/event_queue.py, simpleline/event_loop/signals.py, simpleline/render/__init__.py, simpleline/render/screen/__init__.py, simpleline/render/screen_stack.py
Fixing issues found by a new pylint version.
=> Remove unnecessary pass statements

.packit.yaml
This will make a COPR build and also install package to the container.
This could be enhanced in the future by adding FMF test description.
=> Testing farm seems like a better option

Makefile, setup.py
This will start distribution of the package to the Pypi repository.
=> Add pypi-upload to Makefile

.gitignore, Makefile
We should have a way how to report unit-tests coverage.
=> Add coverage support

Makefile
This branch is not master anymore but stable branch.
=> Use localization from rhel-9 weblate translation component

.github/workflows/validate.yml, .pylintrc, Makefile, simpleline/utils/i18n.py, tests/units/__init__.py, tests/units/main/adv_widgets_test.py
Pylint has a set of new issues raised with the new version. Let's fix these.
=> Fix pylint issues

.github/workflows/validate.yml, Makefile
Let's make run of these tests easier in the future by using a container.
=> Add test execution in a container and GH actions

simpleline/input/input_handler.py, simpleline/render/screen/__init__.py, simpleline/render/screen/input_manager.py, tests/simpleline_tests/adv_widgets_test.py
Backport of https://github.com/rhinstaller/python-simpleline/pull/111 .
=> Add support to disable concurrency check 

.packit.yaml
Packit did some changes which requires changes in the yaml file. Let's fix that.
=> Fix Packit configuration

python-simpleline.spec
Detailed description is here:
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
=> Migrate to SPDX license
